name: Test and Build Application CI

# Проверять тесты и сборку при изменениях в main и в pull request перед merge
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачать код репозитория на runner GitHub Actions
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Использовать ту же основную версию Python, что и в Dockerfile
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # 3. Установить зависимости приложения и тестов
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      # 4. Проверить endpoints приложения автоматическими тестами
      - name: Run application tests
        run: python -m pytest -v

      # 5. Проверить, что Docker image приложения успешно собирается
      - name: Build Docker image
        run: docker build --file Dockerfile --tag devops-junior-project:test .

      # 6. Вывести сообщение после успешного прохождения всех шагов
      - name: Success message
        run: echo "Tests passed and Docker image built successfully!"
